
# author: steeve LAQUITAINE
# purpose: 
#   list and track the pipelines'
#   parameters 

DATA_ENG:
  LABEL: False
  REDUCE_TRAIN: False
  TIMESTEPS: 10
  N_CLASSES: 2
  RESOLUTION: float16
TEST:
TRAIN:
  NAME: BASIC      # BASIC or MIN_SPEECH
  LOSS: CategoricalCrossentropy   # MinSpeechLoss of CategoricalCrossentropy